services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "3000:3000"
    volumes:
     - ./cooking_app:/app
     - node-modules:/app/node_modules
    environment:
     - WATCHPACK_POLLING=true
    tty: true
    stdin_open: true
volumes:
  node-modules:

