services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "3000:3000"
    volumes:
     - ./cooking_app:/app
    environment:
     - WATCHPACK_POLLING=true
    tty: true
    restart: always